### ISSUE TITLE
Request: English description

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [7heaven/bitmapMesh#1]
Please put English description, so that everyone could understand what you wrote...

Also, a small tip: set the targetSdk to be 21 , and use the support library's theme. The current one is as old as API 8...

**Comment by 7heaven** [comment]
thx for your advice

**Comment by 7heaven** [comment]
English description added.

**Comment by AndroidDeveloperLB** [comment]
Thank you. cool library, BTW.
