### ISSUE TITLE
Request: Folding bitmap from left to right

### ISSUE THREAD

**Issue by pwittchen** [7heaven/bitmapMesh#2]
Hi,

First of all, very nice project!
I have one request. Now bitmap is folded from right to left. Can you provide an example with folding bitmap in the opposite direction (from left to right)?

Kind Regards,
Piotr

**Comment by 7heaven** [comment]
I'm currently working on another project now, it's may take some times before i can add new feature to this one. thanks for your kind advice by the way.

**Comment by 7heaven** [comment]
this's just a demo, so I'm not intend to change it.
- I created a new project with this curtain effect view in it, and I add new feature to it so now it can **support folding from right to left and left to right**.the new project address is [CurtainSlidingMenu](http://github.com/7heaven/CurtainSlidingMenu)

**Comment by pwittchen** [comment]
Thanks!
